//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aplication20_07_2019.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Affectation_profils
    {
        public int id_mission_affectation { get; set; }
        public int id_profils_affectation { get; set; }
        public int id_affectation { get; set; }
        public Nullable<int> charge_profil { get; set; }
    
        public virtual Mission Mission { get; set; }
        public virtual Profil Profil { get; set; }
    }
}
