//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aplication20_07_2019.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Marché
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Marché()
        {
            this.Missions = new HashSet<Mission>();
            this.Participations = new HashSet<Participation>();
        }
    
        public string matricule { get; set; }
        public int budget_prevu { get; set; }
        public Nullable<System.DateTime> date_fin { get; set; }
        public Nullable<int> montant_annuel { get; set; }
        public Nullable<int> montant_total { get; set; }
        public string id_responsable_fk { get; set; }
        public string id_prestataire_final { get; set; }
        public Nullable<int> id_projet_fk { get; set; }
        public Nullable<int> Délai { get; set; }
        public Nullable<System.DateTime> date_debut { get; set; }
        public int id_marché { get; set; }
    
        public virtual prestataire prestataire { get; set; }
        public virtual Projet Projet { get; set; }
        public virtual Responsable_marché Responsable_marché { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mission> Missions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Participation> Participations { get; set; }
    }
}
