//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aplication20_07_2019.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class message
    {
        public string id_prestataire_k { get; set; }
        public string id_respo_k { get; set; }
        public string messaage { get; set; }
        public string objet { get; set; }
        public Nullable<System.DateTime> date_msg { get; set; }
        public Nullable<bool> emetteur_prestataire { get; set; }
        public int id_msg { get; set; }
    
        public virtual prestataire prestataire { get; set; }
        public virtual Responsable_marché Responsable_marché { get; set; }
    }
}
