//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aplication20_07_2019.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mission
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Mission()
        {
            this.Affectation_profils = new HashSet<Affectation_profils>();
        }
    
        public int id_mission { get; set; }
        public Nullable<System.DateTime> date_debut_mission { get; set; }
        public Nullable<System.DateTime> date_fin_mission { get; set; }
        public string libelle_mission { get; set; }
        public Nullable<double> charge_jh { get; set; }
        public Nullable<double> cout_ht { get; set; }
        public int id_marche_mission { get; set; }
        public Nullable<int> id_ordreservice_fk { get; set; }
        public Nullable<int> id_domaine_mission_fk { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Affectation_profils> Affectation_profils { get; set; }
        public virtual Domaine Domaine { get; set; }
        public virtual Marché Marché { get; set; }
        public virtual Ordre_service Ordre_service { get; set; }
    }
}
