//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aplication20_07_2019.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class market_appEntities : DbContext
    {
        public market_appEntities()
            : base("name=market_appEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<Affectation_profils> Affectation_profils { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<Domaine> Domaines { get; set; }
        public virtual DbSet<Marché> Marché { get; set; }
        public virtual DbSet<message> messages { get; set; }
        public virtual DbSet<Mission> Missions { get; set; }
        public virtual DbSet<Ordre_service> Ordre_service { get; set; }
        public virtual DbSet<Participation> Participations { get; set; }
        public virtual DbSet<prestataire> prestataires { get; set; }
        public virtual DbSet<Profil> Profils { get; set; }
        public virtual DbSet<Projet> Projets { get; set; }
        public virtual DbSet<Responsable_marché> Responsable_marché { get; set; }
        public virtual DbSet<Participation_profil> Participation_profil { get; set; }
    }
}
