//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aplication20_07_2019.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ordre_service
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ordre_service()
        {
            this.Missions = new HashSet<Mission>();
        }
    
        public Nullable<System.DateTime> date_modification { get; set; }
        public Nullable<System.DateTime> date_debut_ordre { get; set; }
        public Nullable<System.DateTime> date_fin_ordre { get; set; }
        public Nullable<bool> etat_reception { get; set; }
        public Nullable<System.DateTime> date_provisoire { get; set; }
        public Nullable<bool> etat_facturation { get; set; }
        public int id_ordre_service { get; set; }
        public Nullable<int> id_projet_ordreservice { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mission> Missions { get; set; }
        public virtual Projet Projet { get; set; }
    }
}
