//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aplication20_07_2019.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Participation_profil
    {
        public Nullable<int> id_profil_fk { get; set; }
        public Nullable<int> id_participation_fk { get; set; }
        public Nullable<int> cout_unit_ht { get; set; }
        public int id_particip_prof { get; set; }
    
        public virtual Profil Profil { get; set; }
        public virtual Participation Participation { get; set; }
    }
}
