//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aplication20_07_2019.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Participation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Participation()
        {
            this.Participation_profil = new HashSet<Participation_profil>();
        }
    
        public int id_marché_participation { get; set; }
        public string id_prestataire_participation { get; set; }
        public int id_participation { get; set; }
        public Nullable<int> budget_prestation { get; set; }
    
        public virtual Marché Marché { get; set; }
        public virtual prestataire prestataire { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Participation_profil> Participation_profil { get; set; }
    }
}
